# Site settings
title: Van Duc Cuong
baseurl: ""
url: "https://duccuong12.github.io"

# Build settings
markdown: kramdown
plugins: []

timezone: Asia/Ho_Chi_Minh

collections:
  - publications
  - news


defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: null
  - scope:
      path: ""
      type: news
    values:
      layout: null
