# Site settings
title: Van Duc Cuong
baseurl: ""
url: "https://duccuong12.github.io"

# Build settings
markdown: kramdown
plugins: []

timezone: Asia/Ho_Chi_Minh

collections:
  - publications
  - news
